
# === Server Port (optional) ===
server.port=${TPORT}

# === Datasource Configuration for PostgreSQL ===
spring.datasource.url=jdbc:postgresql://${TURL}/${TDB}
spring.datasource.username=${TDB_USERNAME}
spring.datasource.password=${TPW_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA (Hibernate) Configuration for PostgreSQL ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Logging (optional) ===
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE